package org.agentos.runtime.pi

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.agentos.runtime.net.Endpoint
import org.agentos.runtime.ports.ModelSpec

/**
 * `assets/model-catalog.json`, generated by core/pi-runtime/build.mjs from pi-ai's model
 * catalog (format: core/pi-runtime/README.md). Vendor presets for the settings page (F9),
 * MiniMax international / China first, plus templates for custom compatible endpoints.
 *
 * A [CatalogModel] wraps a pi-ai `Model` object unchanged; [CatalogModel.toModelSpec] turns it into the
 * `ports.ModelSpec` that AgentSessionConfig / ModelConfigPort carry. Keys are not part of the catalog or the model: the host binds
 * them to the model's base URL (org.agentos.runtime.net.BaseUrlCredentials).
 */
class ModelCatalog private constructor(
    val schemaVersion: Int,
    val piAiVersion: String?,
    val apis: List<String>,
    val providers: List<Provider>,
    private val templates: Map<String, JsonObject>,
) {
    class Provider(
        val id: String,
        val name: String,
        val apis: List<String>,
        val baseUrls: List<String>,
        /** Label for the key field, for example "MiniMax API key". */
        val keyLabel: String,
        val models: List<CatalogModel>,
    )

    fun provider(id: String): Provider? = providers.firstOrNull { it.id == id }

    fun model(providerId: String, modelId: String): CatalogModel? = provider(providerId)?.models?.firstOrNull { it.id == modelId }

    /**
     * A model for a user-configured endpoint ("自定义兼容端点", F9), built from the template of
     * [api] ("anthropic-messages" or "openai-completions"). [baseUrl] is what the SDK appends
     * its path to: `…/v1` style for OpenAI Chat Completions (`/chat/completions` is added), the
     * API root for Anthropic Messages (`/v1/messages` is added).
     */
    fun customModel(
        api: String,
        id: String,
        baseUrl: String,
        name: String = id,
        contextWindow: Int? = null,
        maxTokens: Int? = null,
        reasoning: Boolean? = null,
        input: List<String>? = null,
    ): CatalogModel {
        val template = templates[api] ?: throw IllegalArgumentException("Unsupported API family: $api (supported: ${templates.keys})")
        require(id.isNotBlank()) { "Model id is blank" }
        val endpoint = Endpoint.parse(baseUrl) ?: throw IllegalArgumentException("Not an absolute http(s) URL: $baseUrl")
        require(endpoint.scheme == "https" || org.agentos.runtime.net.HostFetch.isLoopback(endpoint.host)) {
            "Custom endpoints must use https"
        }
        val fields = template.toMutableMap()
        fields["id"] = JsonPrimitive(id)
        fields["name"] = JsonPrimitive(name)
        fields["baseUrl"] = JsonPrimitive(baseUrl.trim().trimEnd('/'))
        contextWindow?.let { fields["contextWindow"] = JsonPrimitive(it) }
        maxTokens?.let { fields["maxTokens"] = JsonPrimitive(it) }
        reasoning?.let { fields["reasoning"] = JsonPrimitive(it) }
        input?.let { list -> fields["input"] = JsonArray(list.map { JsonPrimitive(it) }) }
        return CatalogModel(JsonObject(fields))
    }

    companion object {
        const val SUPPORTED_SCHEMA_VERSION: Int = 1

        private val json = Json { ignoreUnknownKeys = true }

        fun parse(text: String): ModelCatalog {
            val root = json.parseToJsonElement(text).jsonObject
            val schema = root["schemaVersion"]?.jsonPrimitive?.intOrNull
            require(schema == SUPPORTED_SCHEMA_VERSION) { "model-catalog.json schemaVersion $schema, expected $SUPPORTED_SCHEMA_VERSION" }
            val providers = root["providers"]?.jsonArray.orEmpty().map { p ->
                val o = p.jsonObject
                Provider(
                    id = o.string("id"),
                    name = o.string("name"),
                    apis = o["apis"]?.jsonArray.orEmpty().map { it.jsonPrimitive.content },
                    baseUrls = o["baseUrls"]?.jsonArray.orEmpty().map { it.jsonPrimitive.content },
                    keyLabel = o["auth"]?.jsonObject?.get("label")?.jsonPrimitive?.contentOrNull ?: "${o.string("name")} API key",
                    models = o["models"]?.jsonArray.orEmpty().map { CatalogModel(it.jsonObject) },
                )
            }
            return ModelCatalog(
                schemaVersion = schema,
                piAiVersion = root["generatedFrom"]?.jsonObject?.get("@earendil-works/pi-ai")?.jsonPrimitive?.contentOrNull,
                apis = root["apis"]?.jsonArray.orEmpty().map { it.jsonPrimitive.content },
                providers = providers,
                templates = root["customTemplates"]?.jsonObject.orEmpty().mapValues { it.value.jsonObject },
            )
        }

        private fun JsonObject.string(key: String): String =
            this[key]?.jsonPrimitive?.contentOrNull ?: throw IllegalArgumentException("model-catalog.json: missing \"$key\"")
    }
}

/** A pi-ai `Model` object from the catalog. Fields the host does not understand are kept as they are. */
class CatalogModel(val json: JsonObject) {
    /** The model as the host passes it around (AgentSessionConfig, ModelConfigPort). */
    fun toModelSpec(thinkingLevel: String = "off"): ModelSpec = ModelSpec(json, thinkingLevel)

    val id: String get() = str("id")
    val name: String get() = json["name"]?.jsonPrimitive?.contentOrNull ?: id
    val api: String get() = str("api")
    val provider: String get() = str("provider")
    val baseUrl: String get() = str("baseUrl")
    val reasoning: Boolean get() = json["reasoning"]?.jsonPrimitive?.booleanOrNull ?: false
    val input: List<String> get() = (json["input"] as? JsonArray)?.map { it.jsonPrimitive.content } ?: listOf("text")
    val contextWindow: Int? get() = json["contextWindow"]?.jsonPrimitive?.intOrNull
    val maxTokens: Int? get() = json["maxTokens"]?.jsonPrimitive?.intOrNull

    private fun str(key: String): String = (json[key] as? JsonPrimitive)?.contentOrNull ?: ""

    override fun toString(): String = "CatalogModel($provider/$id, $api, $baseUrl)"
}
