package org.agentos.runtime.pi

import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Deferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.async
import kotlinx.coroutines.cancel
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeout
import kotlinx.coroutines.withTimeoutOrNull
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.int
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put
import org.agentos.runtime.net.FetchRequest
import org.agentos.runtime.net.FetchResponse
import org.agentos.runtime.net.HostFetch
import org.agentos.runtime.net.HostFetchException
import org.agentos.runtime.net.NetErrorKind
import java.security.MessageDigest
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicLong

/** Command / event / host-primitive protocol spoken with `pi-agent.js` (core/pi-runtime/src/host-bridge.js). */
const val PI_PROTOCOL_VERSION: Int = 1

/** The bundle generated by core/pi-runtime/build.mjs (`assets/pi-agent.js`). */
class PiBundle(val source: String, val fileName: String = "pi-agent.js") {
    val sha256: String by lazy {
        MessageDigest.getInstance("SHA-256").digest(source.toByteArray(Charsets.UTF_8)).joinToString("") { "%02x".format(it) }
    }
}

/**
 * Stores QuickJS bytecode compiled from the bundle, so later cold starts skip parsing
 * (S8: ~150 ms from source vs ~15 ms from cached bytecode on the emulator). Keys already
 * include the bundle hash, the engine description and the protocol version.
 */
interface BytecodeCache {
    fun get(key: String): ByteArray?
    fun put(key: String, bytes: ByteArray)
    fun remove(key: String)
}

class InMemoryBytecodeCache : BytecodeCache {
    private val map = ConcurrentHashMap<String, ByteArray>()
    override fun get(key: String): ByteArray? = map[key]
    override fun put(key: String, bytes: ByteArray) { map[key] = bytes }
    override fun remove(key: String) { map.remove(key) }
    val size: Int get() = map.size
}

/**
 * Tool execution and hook decisions requested by Pi. Backed by the Capability Broker, risk
 * policy and Hooks in the adapter (W3 B2). All calls may suspend; they run off the JS thread.
 */
interface PiHost {
    /** Executes a tool. Returns `{content: [...], details?, isError?}` (Pi's tool result shape). */
    suspend fun executeTool(sid: String, toolCallId: String, name: String, args: JsonElement): JsonObject

    /** Pi's `beforeToolCall`: return `{block: true, reason?, terminate?}` to block, or null to allow. */
    suspend fun beforeToolCall(sid: String, toolCallId: String, name: String, args: JsonElement): JsonObject? = null

    /** Pi's `afterToolCall`: return a partial override `{content?, details?, isError?, terminate?}`, or null. */
    suspend fun afterToolCall(
        sid: String,
        toolCallId: String,
        name: String,
        args: JsonElement,
        result: JsonElement,
        isError: Boolean,
    ): JsonObject? = null

    /** The session aborted while [toolCallId] was executing; cancel it best-effort (F6). */
    fun onToolCancelled(sid: String, toolCallId: String) {}
}

/** What happened to one model request, reported after its response head (or failure). */
sealed interface ModelRequestOutcome {
    val sessionId: String?
    val url: String

    class Responded(override val sessionId: String?, override val url: String, val status: Int, val attempts: Int) : ModelRequestOutcome
    class Failed(override val sessionId: String?, override val url: String, val error: HostFetchException) : ModelRequestOutcome
}

interface PiRuntimeListener {
    /**
     * A compacted Pi lifecycle event for session [sid] (core/pi-runtime/README.md, "Events").
     * Called on the JS thread in emission order: hand it off, do not block or do I/O here.
     */
    fun onEvent(sid: String, event: JsonObject)

    fun onModelRequest(outcome: ModelRequestOutcome) {}

    fun onLog(level: String, message: String) {}

    /** The pump ended: [cause] is null after [PiRuntime.close], otherwise why it died (treat as a runtime crash, F8). */
    fun onStopped(cause: Throwable?) {}
}

sealed interface PiRuntimeState {
    data object NotStarted : PiRuntimeState
    data object Starting : PiRuntimeState
    data object Running : PiRuntimeState
    class Stopped(val cause: Throwable?) : PiRuntimeState
}

class PiRuntimeStoppedException(message: String, cause: Throwable? = null) : IllegalStateException(message, cause)

class PiStartup(
    val engine: String,
    val fromBytecode: Boolean,
    val createMs: Double,
    val evalMs: Double,
    val readyMs: Double,
    val protocol: Int,
    val apis: List<String>,
) {
    val totalMs: Double get() = createMs + evalMs + readyMs
    override fun toString(): String =
        "PiStartup(engine=$engine, fromBytecode=$fromBytecode, total=${"%.1f".format(totalMs)}ms, create=${"%.1f".format(createMs)}, eval=${"%.1f".format(evalMs)}, ready=${"%.1f".format(readyMs)})"
}

class PromptResult(
    /** Pi stop reason of the last assistant message: "stop", "toolUse", "length", "aborted", "error". */
    val stopReason: String?,
    val errorMessage: String?,
    /** Text of the last assistant message. */
    val text: String,
    /** Transcript length after this prompt (the system message counts). */
    val messageCount: Int,
    /** Messages appended by this prompt, in order (user, assistant, toolResult, ...). Persist these. */
    val appended: JsonArray,
)

class PiStats(val sessions: Int, val inflightFetches: Int, val activeTimers: Int)

/**
 * One JS runtime running `pi-agent.js` in pump mode (docs/spikes/S8.md b): several Pi `Agent`
 * sessions share it and make progress concurrently. This class owns the message protocol and
 * the host primitives; the engine underneath is a [JsEngine].
 *
 * Lifecycle: [start] once, then [request] (or the typed helpers) from any coroutine, then
 * [close]. If the pump dies (for example an unhandled promise rejection inside JS), [state]
 * becomes [PiRuntimeState.Stopped] with the cause, pending and later requests fail with
 * [PiRuntimeStoppedException], and [PiRuntimeListener.onStopped] fires. Recover like a runtime
 * crash (F8): create a new PiRuntime and rebuild sessions from stored messages; do not replay.
 */
class PiRuntime(
    private val engineFactory: JsEngineFactory,
    private val fetch: HostFetch,
    private val host: PiHost,
    private val listener: PiRuntimeListener,
    private val bytecodeCache: BytecodeCache? = null,
) {
    private val json = Json { ignoreUnknownKeys = true }
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Default)
    private val stateFlow = MutableStateFlow<PiRuntimeState>(PiRuntimeState.NotStarted)
    val state: StateFlow<PiRuntimeState> = stateFlow.asStateFlow()

    private var engine: JsEngine? = null
    private var pumpJob: Job? = null
    private val commands = Channel<String?>(Channel.UNLIMITED)
    private val pending = ConcurrentHashMap<Long, CompletableDeferred<JsonElement>>()
    private val timers = ConcurrentHashMap<Long, CompletableDeferred<String>>()
    private val fetches = ConcurrentHashMap<Long, FetchSlot>()
    private val nextId = AtomicLong(1)
    private val ready = CompletableDeferred<JsonObject>()

    /** Test hook: sees everything that flows into JS (commands, response heads and bodies, host call results). */
    @Volatile
    var ingressObserver: ((ByteArray) -> Unit)? = null

    val activeHostTimers: Int get() = timers.size
    val inflightHostFetches: Int get() = fetches.size

    private class FetchSlot {
        @Volatile var opening: Deferred<FetchResponse>? = null
        @Volatile var response: FetchResponse? = null
        @Volatile var aborted = false
    }

    // ------------------------------------------------------------------ lifecycle

    suspend fun start(bundle: PiBundle, readyTimeoutMs: Long = 30_000): PiStartup {
        check(stateFlow.compareAndSet(PiRuntimeState.NotStarted, PiRuntimeState.Starting)) { "PiRuntime can be started once" }
        try {
            return startInternal(bundle, readyTimeoutMs)
        } catch (e: Throwable) {
            stop(e)
            withContext(NonCancellable) { runCatching { engine?.close() } }
            scope.cancel()
            throw e
        }
    }

    private suspend fun startInternal(bundle: PiBundle, readyTimeoutMs: Long): PiStartup {
        val t0 = System.nanoTime()
        var js = newEngine()
        val cacheKey = "pi-agent:${bundle.sha256}:${js.description}:p$PI_PROTOCOL_VERSION"
        val cached = bytecodeCache?.get(cacheKey)
        val t1 = System.nanoTime()
        var fromBytecode = false
        if (cached != null) {
            fromBytecode = runCatching { js.evaluate(JsScript.Bytecode(cached)) }.isSuccess
            if (!fromBytecode) {
                // Stale or corrupt cache: drop it and start over from source in a clean runtime.
                bytecodeCache?.remove(cacheKey)
                runCatching { js.close() }
                js = newEngine()
            }
        }
        if (!fromBytecode) js.evaluate(JsScript.Source(bundle.source, bundle.fileName))
        val t2 = System.nanoTime()
        pumpJob = scope.launch {
            val cause = try {
                js.evaluate(JsScript.Source("__pi_main()", "pi-main.js"))
                null
            } catch (e: CancellationException) {
                null
            } catch (e: Throwable) {
                e
            }
            stop(cause)
        }
        val hello = withTimeout(readyTimeoutMs) { ready.await() }
        val t3 = System.nanoTime()
        val protocol = hello["protocol"]?.jsonPrimitive?.intOrNull
        if (protocol != PI_PROTOCOL_VERSION) {
            throw IllegalStateException("pi-agent.js speaks protocol $protocol, the host expects $PI_PROTOCOL_VERSION: rebuild core/pi-runtime")
        }
        stateFlow.value = PiRuntimeState.Running
        if (!fromBytecode && bytecodeCache != null) {
            scope.launch { compileToCache(bundle, cacheKey) }
        }
        return PiStartup(
            engine = js.description,
            fromBytecode = fromBytecode,
            createMs = (t1 - t0) / 1e6,
            evalMs = (t2 - t1) / 1e6,
            readyMs = (t3 - t2) / 1e6,
            protocol = protocol,
            apis = hello["apis"]?.jsonArray?.map { it.jsonPrimitive.content }.orEmpty(),
        )
    }

    private fun newEngine(): JsEngine = engineFactory.create().also {
        engine = it
        defineBindings(it)
    }

    private suspend fun compileToCache(bundle: PiBundle, key: String) {
        val tmp = engineFactory.create()
        try {
            tmp.compile(bundle.source, bundle.fileName)?.let { bytecodeCache?.put(key, it) }
        } catch (e: Throwable) {
            listener.onLog("warn", "bytecode compile failed: ${e.message}")
        } finally {
            runCatching { tmp.close() }
        }
    }

    /** Stops the pump (sessions are aborted), releases the engine. Idempotent. */
    suspend fun close() {
        if (stateFlow.value is PiRuntimeState.Running || stateFlow.value is PiRuntimeState.Starting) {
            commands.trySend(null)
            withTimeoutOrNull(5_000) { pumpJob?.join() }
        }
        stop(null)
        withContext(NonCancellable) { runCatching { engine?.close() } }
        scope.cancel()
    }

    private fun stop(cause: Throwable?) {
        val previous = synchronized(this) {
            val current = stateFlow.value
            if (current is PiRuntimeState.Stopped) return
            stateFlow.value = PiRuntimeState.Stopped(cause)
            current
        }
        val error = PiRuntimeStoppedException(
            if (cause == null) "Pi runtime is closed" else "Pi runtime stopped: ${cause.message}",
            cause,
        )
        ready.completeExceptionally(error)
        pending.values.forEach { it.completeExceptionally(error) }
        pending.clear()
        timers.values.forEach { it.complete("cancelled") }
        timers.clear()
        fetches.keys.toList().forEach { abortFetch(it) }
        commands.close()
        if (previous !is PiRuntimeState.NotStarted) listener.onStopped(cause)
    }

    // ------------------------------------------------------------------ commands

    /** Sends one command to the pump and suspends until its reply. */
    suspend fun request(op: String, payload: JsonObject = JsonObject(emptyMap())): JsonElement {
        when (val s = stateFlow.value) {
            is PiRuntimeState.Running -> Unit
            is PiRuntimeState.Stopped -> throw PiRuntimeStoppedException("Pi runtime stopped", s.cause)
            else -> throw IllegalStateException("Pi runtime is not started")
        }
        val id = nextId.getAndIncrement()
        val deferred = CompletableDeferred<JsonElement>()
        pending[id] = deferred
        val cmd = JsonObject(payload + mapOf("id" to JsonPrimitive(id), "op" to JsonPrimitive(op))).toString()
        observe(cmd)
        if (commands.trySend(cmd).isFailure) {
            pending.remove(id)
            throw PiRuntimeStoppedException("Pi runtime stopped")
        }
        return deferred.await()
    }

    suspend fun ping(): JsonObject = request("ping").jsonObject

    /** Creates a Pi `Agent` for [sid]. Pass the stored transcript as [messages] to restore a session. */
    suspend fun createSession(
        sid: String,
        model: JsonObject,
        systemPrompt: String = "",
        tools: JsonArray = JsonArray(emptyList()),
        messages: JsonArray? = null,
        thinkingLevel: String? = null,
    ): Int {
        val reply = request("create", buildJsonObject {
            put("sid", sid)
            put("model", model)
            put("systemPrompt", systemPrompt)
            put("tools", tools)
            if (messages != null) put("messages", messages)
            if (thinkingLevel != null) put("thinkingLevel", thinkingLevel)
        })
        return reply.jsonObject["messages"]?.jsonPrimitive?.int ?: 0
    }

    /** Runs one prompt to Pi's `agent_end`; returns after the whole run including tool rounds. */
    suspend fun prompt(sid: String, text: String, images: JsonArray? = null): PromptResult {
        val reply = request("prompt", buildJsonObject {
            put("sid", sid)
            put("text", text)
            if (images != null) put("images", images)
        }).jsonObject
        return PromptResult(
            stopReason = reply["stopReason"]?.jsonPrimitive?.contentOrNull,
            errorMessage = reply["errorMessage"]?.jsonPrimitive?.contentOrNull,
            text = reply["text"]?.jsonPrimitive?.contentOrNull.orEmpty(),
            messageCount = reply["messageCount"]?.jsonPrimitive?.intOrNull ?: 0,
            appended = reply["appended"]?.jsonArray ?: JsonArray(emptyList()),
        )
    }

    suspend fun abort(sid: String) {
        request("abort", buildJsonObject { put("sid", sid) })
    }

    suspend fun setTools(sid: String, tools: JsonArray) {
        request("setTools", buildJsonObject { put("sid", sid); put("tools", tools) })
    }

    suspend fun setModel(sid: String, model: JsonObject, thinkingLevel: String? = null) {
        request("setModel", buildJsonObject {
            put("sid", sid)
            put("model", model)
            if (thinkingLevel != null) put("thinkingLevel", thinkingLevel)
        })
    }

    /** Full transcript of [sid], system message first. */
    suspend fun history(sid: String): JsonArray = request("history", buildJsonObject { put("sid", sid) }).jsonArray

    suspend fun dispose(sid: String): Boolean =
        request("dispose", buildJsonObject { put("sid", sid) }).jsonObject["disposed"]?.jsonPrimitive?.booleanOrNull == true

    suspend fun stats(): PiStats {
        val o = request("stats").jsonObject
        return PiStats(
            sessions = o["sessions"]?.jsonPrimitive?.intOrNull ?: 0,
            inflightFetches = o["inflightFetches"]?.jsonPrimitive?.intOrNull ?: 0,
            activeTimers = o["activeTimers"]?.jsonPrimitive?.intOrNull ?: 0,
        )
    }

    suspend fun memoryUsage(): JsMemoryUsage? = engine?.memoryUsage()

    // ------------------------------------------------------------------ host primitives

    private fun defineBindings(js: JsEngine) {
        js.defineFunction("__host_emit") { args ->
            onEmit(args[0] as String)
            null
        }
        js.defineAsyncFunction("__host_next") {
            commands.receiveCatching().getOrNull()
        }
        js.defineAsyncFunction("__host_timer") { args ->
            val id = (args[0] as Number).toLong()
            val ms = (args[1] as Number).toLong()
            val signal = CompletableDeferred<String>()
            timers[id] = signal
            try {
                if (ms <= 0) "fired" else withTimeoutOrNull(ms) { signal.await() } ?: "fired"
            } finally {
                timers.remove(id, signal)
            }
        }
        js.defineFunction("__host_timer_cancel") { args ->
            timers.remove((args[0] as Number).toLong())?.complete("cancelled")
            null
        }
        js.defineAsyncFunction("__host_fetch") { args ->
            openFetch((args[0] as Number).toLong(), args[1] as String)
        }
        js.defineAsyncFunction("__host_fetch_read") { args ->
            readFetch((args[0] as Number).toLong())
        }
        js.defineFunction("__host_fetch_abort") { args ->
            abortFetch((args[0] as Number).toLong())
            null
        }
        js.defineAsyncFunction("__host_call") { args ->
            val result = hostCall(args[0] as String, json.parseToJsonElement(args[1] as String).jsonObject)
            val text = result?.toString() ?: "{}"
            observe(text)
            text
        }
    }

    private fun onEmit(text: String) {
        val msg = json.parseToJsonElement(text).jsonObject
        when (msg["t"]?.jsonPrimitive?.contentOrNull) {
            "event" -> listener.onEvent(msg.getValue("sid").jsonPrimitive.content, msg.getValue("e").jsonObject)
            "reply" -> {
                val id = msg["id"]?.jsonPrimitive?.contentOrNull?.toLongOrNull() ?: return
                val deferred = pending.remove(id) ?: return
                if (msg["ok"]?.jsonPrimitive?.booleanOrNull == true) {
                    deferred.complete(msg["value"] ?: JsonNull)
                } else {
                    val e = msg["error"] as? JsonObject
                    deferred.completeExceptionally(
                        JsException(
                            e?.get("message")?.jsonPrimitive?.contentOrNull ?: "JS error",
                            e?.get("stack")?.jsonPrimitive?.contentOrNull,
                        ),
                    )
                }
            }
            "tool_cancel" -> host.onToolCancelled(msg.getValue("sid").jsonPrimitive.content, msg.getValue("toolCallId").jsonPrimitive.content)
            "ready" -> ready.complete(msg)
            "log" -> listener.onLog(msg["level"]?.jsonPrimitive?.contentOrNull ?: "info", msg["msg"]?.jsonPrimitive?.contentOrNull.orEmpty())
        }
    }

    private suspend fun hostCall(method: String, p: JsonObject): JsonObject? {
        val sid = p.getValue("sid").jsonPrimitive.content
        val toolCallId = p["toolCallId"]?.jsonPrimitive?.contentOrNull.orEmpty()
        val name = p["name"]?.jsonPrimitive?.contentOrNull.orEmpty()
        val args = p["args"] ?: JsonObject(emptyMap())
        return when (method) {
            "tool" -> host.executeTool(sid, toolCallId, name, args)
            "beforeToolCall" -> host.beforeToolCall(sid, toolCallId, name, args)
            "afterToolCall" -> host.afterToolCall(
                sid, toolCallId, name, args,
                p["result"] ?: JsonNull,
                p["isError"]?.jsonPrimitive?.booleanOrNull ?: false,
            )
            else -> throw IllegalArgumentException("Unknown host call: $method")
        }
    }

    private suspend fun openFetch(reqId: Long, requestJson: String): String {
        val r = json.parseToJsonElement(requestJson).jsonObject
        val request = FetchRequest(
            url = r.getValue("url").jsonPrimitive.content,
            method = r["method"]?.jsonPrimitive?.contentOrNull ?: "GET",
            headers = r["headers"]?.jsonArray?.map { pair ->
                val a = pair.jsonArray
                a[0].jsonPrimitive.content to a[1].jsonPrimitive.content
            }.orEmpty(),
            body = r["body"]?.takeUnless { it is JsonNull }?.jsonPrimitive?.content,
            sessionId = r["sid"]?.takeUnless { it is JsonNull }?.jsonPrimitive?.contentOrNull,
        )
        val slot = FetchSlot()
        fetches[reqId] = slot
        val opening = scope.async(Dispatchers.IO) { fetch.open(request) }
        slot.opening = opening
        if (slot.aborted) opening.cancel()
        val response = try {
            opening.await()
        } catch (e: HostFetchException) {
            fetches.remove(reqId, slot)
            listener.onModelRequest(ModelRequestOutcome.Failed(request.sessionId, request.url, e))
            throw e
        } catch (e: CancellationException) {
            fetches.remove(reqId, slot)
            if (!slot.aborted) throw e
            throw HostFetchException(NetErrorKind.CANCELED, "aborted")
        }
        if (slot.aborted) {
            response.cancel()
            throw HostFetchException(NetErrorKind.CANCELED, "aborted")
        }
        slot.response = response
        listener.onModelRequest(ModelRequestOutcome.Responded(request.sessionId, request.url, response.status, response.attempts))
        val head = buildJsonObject {
            put("status", response.status)
            put("statusText", response.statusText)
            put("url", response.url)
            put("headers", buildJsonArray {
                for ((n, v) in response.headers) add(buildJsonArray { add(JsonPrimitive(n)); add(JsonPrimitive(v)) })
            })
        }.toString()
        observe(head)
        return head
    }

    private suspend fun readFetch(reqId: Long): ByteArray? {
        val slot = fetches[reqId] ?: return null
        val response = slot.response ?: return null
        val chunk = try {
            response.read()
        } catch (e: Exception) {
            fetches.remove(reqId, slot)
            throw e
        }
        if (chunk == null) {
            fetches.remove(reqId, slot)
        } else {
            ingressObserver?.invoke(chunk)
        }
        return chunk
    }

    private fun abortFetch(reqId: Long) {
        val slot = fetches.remove(reqId) ?: return
        slot.aborted = true
        slot.opening?.cancel()
        slot.response?.cancel()
    }

    private fun observe(text: String) {
        ingressObserver?.invoke(text.toByteArray(Charsets.UTF_8))
    }
}
