// Builds the Pi Agent core bundle for the AgentOS :agent process.
//
//   node build.mjs [--target es2022] [--no-minify] [--out-dir <assets dir>] [--report-dir <dir>] [--quiet]
//
// Outputs (generated, not committed; see .gitignore):
//   app/src/main/assets/pi-agent.js          single IIFE, run by QuickJS (JsEngine)
//   app/src/main/assets/model-catalog.json   vendor presets from pi-ai's catalog (format: README.md)
//   build/build-report.json, build/meta.json sizes, versions, stubbed modules
//
// pi-ai is limited to the anthropic-messages and openai-completions API families;
// Node built-ins are replaced by src/node-stubs/ (docs/spikes/S8.md a). Defaults
// (es2022, minified) are what S8 measured on device; --no-minify for readable stacks.
import * as esbuild from "esbuild";
import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const opt = (name, fallback) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : fallback;
};
const outDir = path.resolve(here, opt("--out-dir", "../../app/src/main/assets"));
const reportDir = path.resolve(here, opt("--report-dir", "build"));
const target = opt("--target", "es2022");
const minify = !args.includes("--no-minify");
const quiet = args.includes("--quiet");
const log = (...a) => { if (!quiet) console.log(...a); };

const PI_AI_DIR = path.resolve(here, "node_modules/@earendil-works/pi-ai/dist");
const PI_CORE_DIR = path.resolve(here, "node_modules/@earendil-works/pi-agent-core");
const SUPPORTED_APIS = ["anthropic-messages", "openai-completions"];
const CATALOG_SCHEMA_VERSION = 1;

if (!fs.existsSync(PI_CORE_DIR)) {
  console.error("core/pi-runtime/node_modules is missing: run `npm ci` in core/pi-runtime first.");
  process.exit(1);
}

const versions = Object.fromEntries(
  ["@earendil-works/pi-agent-core", "@earendil-works/pi-ai", "@anthropic-ai/sdk", "openai", "typebox"].map((p) => [
    p,
    JSON.parse(fs.readFileSync(path.resolve(here, "node_modules", p, "package.json"), "utf8")).version,
  ]),
);
const protocolVersion = Number(/export const PROTOCOL_VERSION = (\d+);/.exec(fs.readFileSync(path.join(here, "src/host-bridge.js"), "utf8"))[1]);

// ---------------------------------------------------------------------------
// 1. Bundle
// ---------------------------------------------------------------------------
const stubbed = [];
const stub = (file) => path.resolve(here, "src/node-stubs", file);
const nodeStubs = {
  name: "agentos-node-stubs",
  setup(build) {
    build.onResolve({ filter: /(^|\/)internal\/node\.mjs$/ }, (a) => {
      if (!a.importer.includes("@anthropic-ai/sdk")) return undefined;
      stubbed.push(`@anthropic-ai/sdk/internal/node.mjs  <- ${path.relative(here, a.importer)}`);
      return { path: stub("anthropic-internal-node.js") };
    });
    build.onResolve({ filter: /agent-toolset\/node\.mjs$/ }, (a) => {
      stubbed.push(`@anthropic-ai/sdk/tools/agent-toolset/node.mjs  <- ${path.relative(here, a.importer)}`);
      return { path: stub("anthropic-agent-toolset-node.js") };
    });
    build.onResolve({ filter: /(^|\/)provider-env\.js$/ }, (a) => {
      if (!a.importer.includes("pi-ai")) return undefined;
      stubbed.push(`@earendil-works/pi-ai/dist/utils/provider-env.js  <- ${path.relative(here, a.importer)}`);
      return { path: stub("pi-ai-provider-env.js") };
    });
    build.onResolve({ filter: /^node:/ }, (a) => {
      stubbed.push(`UNEXPECTED ${a.path}  <- ${path.relative(here, a.importer)}`);
      return { path: stub("node-builtin.js") };
    });
  },
};

fs.mkdirSync(outDir, { recursive: true });
fs.mkdirSync(reportDir, { recursive: true });
const bundlePath = path.join(outDir, "pi-agent.js");
const started = Date.now();
const result = await esbuild.build({
  entryPoints: [path.resolve(here, "src/entry.js")],
  bundle: true,
  format: "iife",
  platform: "neutral",
  target,
  minify,
  mainFields: ["module", "main"],
  conditions: ["import", "default"],
  alias: { "pi-agent-core/agent": path.join(PI_CORE_DIR, "dist/agent.js") },
  plugins: [nodeStubs],
  banner: {
    js: `/* AgentOS pi-agent.js — generated by core/pi-runtime/build.mjs, do not edit. protocol=${protocolVersion} ` +
      Object.entries(versions).map(([k, v]) => `${k}@${v}`).join(" ") + " */",
  },
  outfile: bundlePath,
  metafile: true,
  legalComments: "none",
  logLevel: "warning",
});

const bundle = fs.readFileSync(bundlePath);
fs.writeFileSync(path.join(reportDir, "meta.json"), JSON.stringify(result.metafile));

const byPackage = new Map();
for (const [file, info] of Object.entries(Object.values(result.metafile.outputs)[0].inputs)) {
  const m = /node_modules\/((?:@[^/]+\/)?[^/]+)/.exec(file);
  const key = m ? m[1] : "(agentos src)";
  byPackage.set(key, (byPackage.get(key) ?? 0) + info.bytesInOutput);
}
const unexpected = stubbed.filter((s) => s.startsWith("UNEXPECTED"));
const bundleText = bundle.toString("utf8");
const forbidden = [/\beval\(/, /\bnew Function\(/].filter((re) => re.test(bundleText)).map(String);

// ---------------------------------------------------------------------------
// 2. model-catalog.json (vendor presets) from pi-ai's catalog, two families only
// ---------------------------------------------------------------------------
const PRESET_ORDER = ["minimax", "minimax-cn"]; // MiniMax international / China first (F9)
// Subscription-account providers: their "key" is a login token, and v1 has no subscription login (F9).
const EXCLUDED_PROVIDERS = { "github-copilot": "subscription account (GitHub Copilot token / OAuth), not supported in v1" };
const providersDir = path.join(PI_AI_DIR, "providers");
const providerFiles = fs
  .readdirSync(providersDir)
  .filter((f) => f.endsWith(".js") && !f.endsWith(".models.js") && !f.endsWith(".map"))
  .sort();
const providers = [];
const skipped = [];
for (const file of providerFiles) {
  const mod = await import(pathToFileURL(path.join(providersDir, file)).href);
  const factories = Object.entries(mod).filter(([name, fn]) => typeof fn === "function" && /Provider$/.test(name) && fn.length === 0);
  for (const [, factory] of factories) {
    let p;
    try { p = factory(); } catch { continue; }
    if (!p || typeof p.getModels !== "function" || !p.id) continue;
    if (EXCLUDED_PROVIDERS[p.id]) { skipped.push(`${p.id}: ${EXCLUDED_PROVIDERS[p.id]}`); continue; }
    const models = p.getModels().filter((m) => SUPPORTED_APIS.includes(m.api));
    if (models.length === 0) continue;
    if (!p.auth?.apiKey) { skipped.push(`${p.id}: no API-key auth`); continue; }
    if (typeof p.headers === "function") { skipped.push(`${p.id}: dynamic provider headers`); continue; }
    const baseUrls = [...new Set(models.map((m) => m.baseUrl))];
    if (baseUrls.some((u) => !/^https:\/\//.test(u ?? "") || /[{}]/.test(u))) { skipped.push(`${p.id}: templated/unknown baseUrl`); continue; }
    providers.push({
      id: p.id,
      name: p.name,
      apis: [...new Set(models.map((m) => m.api))],
      baseUrls,
      auth: { type: "api-key", label: p.auth.apiKey.name ?? `${p.name} API key` },
      models,
    });
  }
}
providers.sort((a, b) => {
  const ia = PRESET_ORDER.indexOf(a.id), ib = PRESET_ORDER.indexOf(b.id);
  if (ia >= 0 || ib >= 0) return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib);
  return a.id.localeCompare(b.id);
});
if (providers[0]?.id !== "minimax" || providers[1]?.id !== "minimax-cn") {
  console.error(`model catalog: MiniMax presets must come first, got ${providers.slice(0, 2).map((p) => p.id)}`);
  process.exit(3);
}

const catalog = {
  schemaVersion: CATALOG_SCHEMA_VERSION,
  generatedFrom: { "@earendil-works/pi-ai": versions["@earendil-works/pi-ai"] },
  apis: SUPPORTED_APIS,
  // Templates for a "custom compatible endpoint": the host fills id, name, baseUrl (and may override limits).
  customTemplates: {
    "anthropic-messages": { api: "anthropic-messages", provider: "custom", reasoning: false, input: ["text", "image"], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 8192 },
    "openai-completions": { api: "openai-completions", provider: "custom", reasoning: false, input: ["text", "image"], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 8192 },
  },
  providers,
};
const catalogJson = JSON.stringify(catalog);
fs.writeFileSync(path.join(outDir, "model-catalog.json"), catalogJson);

// ---------------------------------------------------------------------------
// 3. Report
// ---------------------------------------------------------------------------
const kb = (n) => `${(n / 1024).toFixed(1)} KB`;
const report = {
  protocolVersion,
  catalogSchemaVersion: CATALOG_SCHEMA_VERSION,
  target,
  minify,
  buildMs: Date.now() - started,
  versions,
  outputs: { bundle: path.relative(here, bundlePath), catalog: path.relative(here, path.join(outDir, "model-catalog.json")) },
  bundleBytes: bundle.length,
  bundleGzipBytes: gzipSync(bundle).length,
  bundleSha256: createHash("sha256").update(bundle).digest("hex"),
  catalogBytes: Buffer.byteLength(catalogJson),
  catalogGzipBytes: gzipSync(catalogJson).length,
  catalogProviders: providers.length,
  catalogModels: providers.reduce((a, p) => a + p.models.length, 0),
  stubbed: [...new Set(stubbed)],
  skippedProviders: skipped,
  forbiddenConstructs: forbidden,
  sizeByPackage: Object.fromEntries([...byPackage.entries()].sort((a, b) => b[1] - a[1])),
};
fs.writeFileSync(path.join(reportDir, "build-report.json"), JSON.stringify(report, null, 2));
log(`pi-agent.js        ${kb(report.bundleBytes)} (gzip ${kb(report.bundleGzipBytes)})  target=${target} minify=${minify} protocol=${protocolVersion}  -> ${report.outputs.bundle}`);
log(`model-catalog.json ${kb(report.catalogBytes)} (gzip ${kb(report.catalogGzipBytes)})  ${report.catalogProviders} providers / ${report.catalogModels} models, schemaVersion=${CATALOG_SCHEMA_VERSION}`);
if (!quiet) {
  log("size by package:");
  for (const [k, v] of Object.entries(report.sizeByPackage)) log(`  ${k.padEnd(36)} ${kb(v)}`);
  log("stubbed modules:");
  for (const s of report.stubbed) log(`  ${s}`);
  if (skipped.length) log(`providers skipped: ${skipped.join("; ")}`);
}
if (unexpected.length) {
  console.error(`Unexpected Node built-in imports were stubbed; review before shipping:\n  ${unexpected.join("\n  ")}`);
  process.exitCode = 2;
}
if (forbidden.length) {
  console.error(`The bundle contains ${forbidden.join(", ")}; QuickJS eval is meant to stay unused (architecture principle 8).`);
  process.exitCode = 2;
}
