plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

// Throwaway spike keys generated by spikes/S2/build.sh into build/keys/ (never committed).
// The password is the public Android debug-key convention, not a secret; override with SPIKE_KEY_PASS.
val spikeKeyPass: String = System.getenv("SPIKE_KEY_PASS") ?: "android"

android {
    // Class names mirror the real AgentOS App (org.agentos.app.*) so the component names in the
    // supervision contract can be tested as-is; the applicationId differs so the spike never
    // collides with the real App or its permissions on a test device.
    namespace = "org.agentos.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "org.agentos.spike.s2"
        minSdk = 35
        targetSdk = 36
        versionCode = 1
        versionName = "s2-1"
        // START_STICKY vs START_NOT_STICKY for AgentService, see docs/spikes/S2.md case K3.
        buildConfigField("boolean", "STICKY", (findProperty("s2.sticky") ?: "false").toString())
    }

    signingConfigs {
        create("spikeA") {
            storeFile = rootProject.file("build/keys/spike-a.jks")
            storePassword = spikeKeyPass
            keyAlias = "spike"
            keyPassword = spikeKeyPass
        }
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.getByName("spikeA")
        }
    }

    buildFeatures {
        aidl = true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}
